---
debian:
  packages:
    ntp_client:
      - ntp
      - ntpdate
      - ntpstat
    sitewide:
      - aptitude
      - package: prometheus-node-exporter
        enable_service: prometheus-node-exporter
      - screen
      - vim-nox
      - vim-addon-manager
      - vim-scripts
      - tcsh
      - zsh

