---
site_config:
  cron_apt:
    hour: "4"
  dnsmasq:
    site: "ipmu"
  elastic:
    server: "elasticsearch"
    storage_nfs: "10.100.200.3:/server/services/elasticsearch"
  git:
    key_file: "~/.ssh/id_rsa"
  grafana:
    url: "https://pfs.ipmu.jp/internal/monitors/grafana/"
  httpd:
    sites_git: "git@github.com:/Subaru-PFS/pfs_ipmu_config.git"
  influxdb:
    storage_nfs: "10.100.200.3:/server/services/influxdb"
  ldap:
    uri: "ldap://ldap.pfs.ipmu.jp/"
    base: "dc=shell,dc=pfs,dc=ipmu,dc=jp"
  mail:
    notice_from: "pfs@pfs.ipmu.jp"
    notice_name: "PFS IPMU System"
    smarthost: "smarthost.pfs.ipmu.jp"
  mysql:
    data_directory: "/services/mysql/"
  nfs:
    common:
      - source: "10.100.200.4:/data1"
        target: "/data1"
      - source: "10.100.200.3:/server/home"
        target: "/home"
    v3export_access: "10.100.200.0/23(rw,sync,no_subtree_check,no_root_squash)"
  ntp: 
    upstream: "157.82.226.81"
    local: ntp.pfs.ipmu.jp
  packages:
    sitewide:
      - aptitude
      - package: prometheus-node-exporter
        enable_service: prometheus-node-exporter
      - screen
      - vim-nox
      - vim-addon-manager
      - vim-scripts
      - tcsh
      - zsh
    host_pfsarch:
      - apache2
      - at
      - bc
      - certbot
      - dnsutils
      - fail2ban
      - gawk
      - nfs-kernel-server
      - open-iscsi
      - parted
      - patch
      - python-certbot-apache
      - rsync
      - w3m
    utils_astro:
      - libcfitsio-bin
      - libcfitsio-dev
      - python-fitsio
      - python3-fitsio
    utils_basic:
      - at
      - bc
      - cadaver
      - curl
      - dnsutils
      - ftp-ssl
      - gawk
      - git
      - git-lfs
      - httping
      - lv
      - lynx
      - nslcd
      - nslcd-utils
      - patch
      - patchutils
      - rsync
      - sharutils
      - sslscan
      - telnet-ssl
      - time
      - w3m
      - wdiff
      - whois
      - xterm
    utils_dev:
      - alien
      - devscripts
      - dh-make-perl
      - fakeroot
      - git-buildpackage
    utils_latex:
      - cjk-latex
      - dvi2ps
      - ghostscript
      - gsfonts
      - latex-cjk-all
      - latexdiff
      - ps2eps
      - pstoedit
      - psutils
      - texlive
      - texlive-extra-utils
      - texlive-fonts-extra
      - texlive-generic-extra
      - texlive-lang-cjk
      - texlive-latex-extra
      - texlive-math-extra
      - texlive-metapost
      - texlive-pictures
      - texlive-plain-extra
      - texlive-pstricks
      - texlive-science
    utils_media:
      - ffmpeg
      - fuseiso9660
      - genisoimage
      - gimp
      - gmt
      - gmt-doc
      - gmt-gshhg-full
      - gmt-gshhg-high
      - gmt-gshhg-low
      - gnuplot
      - graphviz
      - imagemagick
      - mplayer2
      - netpbm
      - vlc
    utils_mgmt:
      - ipmitool
      - libvirt-clients
      - ldap-utils
      - openipmi
      - parted
    utils_normalwork:
      - a2ps
      - altermime
      - aspell-en
      - cups
      - cups-filters
      - cups-pdf
      - cups-ppdc
      - ethtool
      - fetchmail
      - mariadb-client
      - mscompress
      - net-tools
      - netcat-openbsd
      - p7zip-full
      - pbzip2
      - printer-driver-cups-pdf
      - printer-driver-gutenprint
      - rpm2cpio
      - shared-mime-info
      - smitools
      - snmp
      - strace
      - subversion
    utils_python2:
      - python-all
      - python-astropy
      - python-crypto
      - python-dateutil
      - python-dev
      - python-html5lib
      - python-imaging
      - python-jinja2
      - python-libvirt
      - python-magic
      - python-markupsafe
      - python-matplotlib
      - python-nose
      - python-numpy
      - python-oauth
      - python-openssl
      - python-pil
      - python-pip
      - python-pycurl
      - python-pyparsing
      - python-pysnmp4
      - python-pythonmagick
      - python-scipy
      - python-serial
      - python-setuptools
      - python-simplejson
      - python-sphinx
      - python-talloc
      - python-tk
      - python-twisted
      - python-tz
      - python-urllib3
      - python-wadllib
      - python-wheel
      - python-wstools
    utils_python3:
      - python3-all
      - python3-astropy
      - python3-crypto
      - python3-dateutil
      - python3-dev
      - python3-html5lib
      - python3-jinja2
      - python3-libvirt
      - python3-magic
      - python3-markupsafe
      - python3-matplotlib
      - python3-nose
      - python3-numpy
      - python3-oauth
      - python3-openssl
      - python3-pil
      - python3-pip
      - python3-pycurl
      - python3-pyparsing
      - python3-pysnmp4
      - python3-pythonmagick
      - python3-scipy
      - python3-serial
      - python3-setuptools
      - python3-simplejson
      - python3-sphinx
      - python3-tk
      - python3-twisted
      - python3-tz
      - python3-urllib3
      - python3-wadllib
      - python3-wheel
  postfix:
    tls: 
      use: False
      cert_file: ""
      key_file: ""
      CAfile: ""
    myhostname: "pfs.ipmu.jp"
    localnet: "10.100.200.0/23"
  postgres:
    connect_from: "10.100.200.0/23"
    data_directory: "/services/postgresql/"
    postgres_conf:
      - label: log_min_messages
        value: warning
      - label: syslog_facility
        value: LOCAL0
      - label: log_destination
        value: syslog
  prometheus:
    server: "prometheus"
    external_url: "https://pfs.ipmu.jp/internal/monitors/prometheus/"
    route_prefix: "/internal/monitors/prometheus"
    log_format: "logger:syslog?appname=prometheus&local=7"
    storage_nfs: "10.100.200.3:/server/services/prometheus"
  prometheus_exporter:
    mysql:
      host: "mysql:3306"
    pgsql:
      host: "pgsql:5432"
    es:
      host: "elasticsearch"
    jira:
      host: "localhost"
  rsyslog:
    server: "rsyslog.pfs.ipmu.jp"
    repush: "10.100.200.14:10514;json-template"
  samba:
    workgroup: "PFS"
    address: "10.100.200.0/23 192.168.0.0/16"
    printer_group: "root, @alls"
    export:
      name: "data1"
      comment: "Data Storage 1"
      path: "/data1"
  squid:
    cache_mem: "1 GB"
    maximum_object_size_in_memory: "2 MB"
    maximum_object_size: "20 MB"
    cache_dir: "/squid"
    cache_dir_mb: 20000
    cache_dir_nfs: "10.100.200.3:/server/services/squid/"
    syslog: "local1.info"
  system_accounts:
    defuser_groups: "adm,dialout,cdrom,audio,netdev"
    groups:
      - gname: "libvirt-qemu"
        gid: 200
      - gname: "munin"
        gid: 201
      - gname: "mysql"
        gid: 202
      - gname: "postgres"
        gid: 203
      - gname: "kvm"
        gid: 204
      - gname: "prometheus"
        gid: 205
      - gname: "grafana"
        gid: 206
      - gname: "elasticsearch"
        gid: 207
      - gname: "logstash"
        gid: 208
      - gname: "influxdb"
        gid: 209
    users:
      - uname: "libvirt-qemu"
        uid: 200
        home: "/var/lib/libvirt"
        group: "libvirt-qemu"
        groups: "kvm"
      - uname: "munin"
        uid: 201
        home: "/var/lib/munin"
        group: "munin"
      - uname: "mysql"
        uid: 202
        home: "/var/lib/mysql"
        group: "mysql"
      - uname: "postgres"
        uid: 203
        home: "/var/lib/postgres"
        group: "postgres"
        shell: "/bin/bash"
      - uname: "prometheus"
        uid: 204
        group: "prometheus"
        home: "/var/lib/prometheus"
        shell: "/bin/false"
      - uname: "grafana"
        uid: 205
        group: "grafana"
        home: "/usr/share/grafana"
        shell: "/bin/false"
      - uname: "elasticsearch"
        uid: 206
        group: "elasticsearch"
        home: "/home/elasticsearch"
        shell: "/bin/false"
      - uname: "logstash"
        uid: 207
        group: "logstash"
        home: "/usr/share/logstash"
        shell: "/usr/sbin/nologin"
      - uname: "influxdb"
        uid: 208
        group: "influxdb"
        home: "/var/lib/influxdb"
        shell: "/bin/false"
  system_dirs:
    backup_nfs: "pd2:/server/backup/"
    backup_dir: "/server/backup/"
    git_clone: "/usr/local/gitrepo/"
  virt:
    nfsdisk: "10.100.200.3:/virt"
    pki:
      local: "/virt/pki/"
      subj: "/C=JP/ST=Chiba/L=Kashiwa/O=PFS"

