---
- name: System wide groups
  become: yes
  group: 
    name: "{{ item.gname }}"
    gid: "{{ item.gid }}"
    state: present
    system: yes
  with_items: "{{ site_config.system_accounts.groups }}"
- name: System wide account
  become: yes
  user:
    name: "{{ item.uname }}"
    uid: "{{ item.uid }}"
    createhome: yes
    home: "{{ item.home | default(omit) }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups | default(omit) }}"
    state: present
    system: yes
    password: no
    shell: "{{ item.shell | default(omit) }}"
  with_items: "{{ site_config.system_accounts.users }}"
- name: Add running account to system groups
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups: "{{ site_config.system_accounts.defuser_groups }}"
    append: yes

