---
- name: Configure iptables v4
  become: yes
  lineinfile:
    dest: "/etc/iptables/rules.v4"
    line: "{{ item }}"
    insertafter: "^# ANSIBLE_ROLE_FILTER_PLACE"
  with_items:
    - "-A INPUT -p tcp -m tcp --dport 995 -j ACCEPT"
  notify: restart iptables-persistent
- name: Configure iptables v6
  become: yes
  lineinfile:
    dest: "/etc/iptables/rules.v6"
    line: "{{ item }}"
    insertafter: "^# ANSIBLE_ROLE_FILTER_PLACE"
  with_items:
    - "-A INPUT -p tcp -m tcp --dport 995 -j ACCEPT"
  notify: restart iptables-persistent


