---
- name: restart apache2
  systemd:
    name: apache2.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
- name: restart iptables-persistent
  systemd:
    name: netfilter-persistent.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes


