---
- name: restart postfix
  systemd:
    name: postfix.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
- name: restart netfilter-persistent
  systemd:
    name: netfilter-persistent.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

