---
- name: Configure grafana.ini (no need hand edit, initial startup takes up to 5min)
  become: yes
  ini_file:
    dest: /etc/grafana/grafana.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: "server"
      option: "domain"
      value: "{{ ansible_dns.domain }}"
    - section: "server"
      option: "root_url"
      value: "{{ site_config.grafana.url }}"
    - section: "users"
      option: "allow_sign_up"
      value: "false"
    - section: "auth.anonymous"
      option: "enabled"
      value: "true"
    - section: "smtp"
      option: "enabled"
      value: "true"
    - section: "smtp"
      option: "host"
      value: "{{ site_config.mail.smarthost }}:25"
    - section: "smtp"
      option: "from_address"
      value: "{{ site_config.mail.notice_from }}"
    - section: "smtp"
      option: "from_name"
      value: "{{ site_config.mail.notice_name }} Grafana"
    - section: "log"
      option: "mode"
      value: "syslog"
    - section: "log"
      option: "level"
      value: "warn"
    - section: "database"
      option: "type"
      value: "mysql"
    - section: "database"
      option: "host"
      value: "{{ site_config.grafana.db.host }}"
    - section: "database"
      option: "name"
      value: "{{ site_config.grafana.db.name }}"
    - section: "database"
      option: "user"
      value: "{{ site_config.grafana.db.name }}"
    - section: "database"
      option: "password"
      value: "{{ site_config.grafana.db.name }}"
    - section: "session"
      option: "provider"
      value: "mysql"
    - section: "session"
      option: "provider_config"
      value: "{{ site_config.grafana.db.name }}:{{ site_config.grafana.db.name }}@tcp({{ site_config.grafana.db.host }})/{{ site_config.grafana.db.name }}"
  notify: restart grafana

