---
- name: Add https for apt
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - debian-archive-keyring
- name: Download apt-source config file
  become: yes
  get_url:
    url: "https://packagecloud.io/install/repositories/grafana/stable/config_file.list?os={{ ansible_os_family }}&dist={{ ansible_lsb.codename }}"
    dest: /etc/apt/sources.list.d/grafana.conf
- name: Add package cloud apt-key
  become: yes
  apt_key:
    url: "https://packagecloud.io/grafana/stable/gpgkey"
    state: present
- name: Grafana package
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - grafana
- name: Configure grafana.ini (NEED HAND EDIT FOR database, session, security, auth)
  become: yes
  ini_file:
    dest: /etc/grafana/grafana.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: "server"
      option: "domain"
      value: "{{ ansible_dns.domain }}"
    - section: "server"
      option: "root_url"
      value: "{{ site_config.grafana.url }}"
    - section: "users"
      option: "allow_sign_up"
      value: "false"
    - section: "auth.anonymous"
      option: "enabled"
      value: "true"
    - section: "smtp"
      option: "enabled"
      value: "true"
    - section: "smtp"
      option: "host"
      value: "{{ site_config.mail.smarthost }}:25"
    - section: "smtp"
      option: "from_address"
      value: "{{ site_config.mail.notice_from }}"
    - section: "smtp"
      option: "from_name"
      value: "{{ site_config.mail.notice_name }} Grafana"
    - section: "log"
      option: "mode"
      value: "syslog"
    - section: "log"
      option: "level"
      value: "warn"
  notify: restart grafana

