---
- hosts: all
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
    - "group_vars/debian-packages_{{ ansible_distribution_release }}.yml"
  roles:
    - iptables
#    - localnet
    - system-accounts
    - role: packages
      packages: "{{ debian.packages.sitewide }}"
    - cron-apt
    - ssh-gateway
    - role: ntp-client
      when: "server_ntp is undefined"
    - role: exim4
      when: "server_smarthost is undefined"
    - role: rsyslog-client
      when: "server_rsyslog is undefined and rsyslog is defined"

- hosts: server
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
    - "group_vars/debian-packages_{{ ansible_distribution_release }}.yml"
  vars_prompt:
    - name: "l2tp_vpn_psk"
      prompt: "L2TP/IPSec VPN PSK.\n  Just type enter when you don't configure"
  roles:
    - { role: mount, when: "local_uuids is defined" }
    - { role: ntp-server, when: "server_ntp is defined" }
    - { role: rsyslog-server, when: "server_rsyslog is defined" }
    - { role: ldap-server, when: "server_ldap is defined" }
    - { role: dnsmasq, when: "server_dnsmasq is defined" }
    - { role: prometheus, when: "server_prometheus is defined" }
    - { role: grafana, when: "server_grafana is defined" }
    - { role: apache, when: "server_apache is defined" }
    - { role: certbot, when: "server_apache is defined or server_nginx is defined" }
    - { role: couchdb, when: "server_couchdb is defined" }
    - { role: l2tp, when: "server_l2tp is defined" }
    - { role: squid, when: "server_squid is defined" }
    - { role: pgsql-server, when: "pgsql_server is defined" }
    - { role: mysql-server, when: "mysql_server is defined" }

- hosts: workshell
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
    - "group_vars/debian-packages_{{ ansible_distribution_release }}.yml"
  roles:
    - ldap-client
    - role: nfs-client
      when: "nfsv3_target is defined"
    - role: packages
      packages: "{{ debian.packages.basic }}"
    - role: packages
      packages: "{{ debian.packages.dev }}"
    - role: packages
      packages: "{{ debian.packages.dev_go }}"
    - role: packages
      packages: "{{ debian.packages.media }}"
    - role: packages
      packages: "{{ debian.packages.normalwork }}"
    - role: packages
      packages: "{{ debian.packages.python3 }}"




######### WILL BE UPDATED

#- hosts: external
#  vars_files:
#    - "group_vars/site_{{ ansible_domain }}.yml"
#    - "group_vars/debian-packages_{{ ansible_distribution_release }}.yml"
#  roles:

- hosts: prometheus-exporters
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  vars_prompt:
    - name: "prometheus_exporters_mysql_account"
      prompt: "(prometheus_exporters_mysql_account)\nEnter account information for mysql in \"<account>:<password>\" format\n  need 'select' and 'replication client' priv on *.*\n  just type enter when you don't configure"
      private: yes
    - name: "prometheus_exporters_pgsql_account"
      prompt: "prometheus_exporters_pgsql_account)\nEnter account information for pgsql in \"<account>:<password>\" format\n  need connection priv on postgres\n  just type enter when you don't configure"
      private: yes
  roles:
    - prometheus-exporters

- hosts: works
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - ldap-client
    - role: nodejs
      when: "install_nodejs is defined"
    - role: nfs-client
      when: "nfsv3_target is defined"

- hosts: samba
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - ldap-client
    - role: nfs-client
      when: "nfsv3_target is defined"
    - samba-server


- hosts: hw-server
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - hwraid
    - iscsi
    - role: nfs-server
      when: nfs_user_region is defined
    - role: ldap-client
      when: nfs_user_region is defined


- hosts: virt-host
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - virt-server
- hosts: virt-client
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - virt-client

- hosts: privca
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - privca

- hosts: landfill
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - boot-aptupdate
    - serial-console
    - { role: packages, packages: "{{ host_packages }}" }

- hosts: jupyter
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - jupyter

- hosts: nfssrv
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - nfs-server
    - ldap-client

- hosts: fc-nfs
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - iscsi
    - nfs-server


