---
- hosts: normalwork
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: packages, packages: "{{ site_config.packages.utils_astro }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_basic }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_dev }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_latex }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_media }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_mgmt }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_normalwork }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_python2 }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_python3 }}" }
    - ldap-client
    - { role: nfs-client, nfsv3_target: "{{ site_config.nfs.common }}" }

- hosts: melco
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: packages, packages: "{{ site_config.packages.utils_basic }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_dev }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_normalwork }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_python3 }}" }

- hosts: nfssrv
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - nfs-server
    - ldap-client

- hosts: pfsarch
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: packages, packages: "{{ site_config.packages.host_pfsarch }}" }
    - { role: fail2ban, jail_enable: [ sshd, apache-auth ] }

- hosts: pfscalc
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - mount
    - nat-route
    - samba-server

- hosts: pfsdisk
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - mount

- hosts: lfsrv
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: nfs-client, nfsv3_target: "{{ nfs_mount }}" }
    - apache

- hosts: dbsrv
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - role: mount
      when: "local_uuids is defined"
    - role: pgsql-server
      when: "pgsql_server is defined"
    - role: mysql-server
      when: "mysql_server is defined"

- hosts: cuda
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - cuda

