---
- hosts: melco
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: packages, packages: "{{ site_config.packages.utils_basic }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_dev }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_normalwork }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_python3 }}" }

- hosts: nfssrv
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - nfs-server
    - ldap-client

- hosts: pfsarch
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: packages, packages: "{{ site_config.packages.host_pfsarch }}" }
    - { role: fail2ban, jail_enable: [ sshd, apache-auth ] }

- hosts: pfscalc
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - mount
    - nat-route
    - samba-server

- hosts: pfsdisk
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - mount

- hosts: lfsrv
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: nfs-client, nfsv3_target: "{{ nfs_mount }}" }
    - apache

- hosts: cuda
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - cuda

