---
- hosts: normalwork
  vars_files:
    - "group_vars/site_{{ ansible_domain }}.yml"
  roles:
    - { role: packages, packages: "{{ site_config.packages.utils_astro }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_basic }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_dev }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_latex }}", when: "utils_latex is defined" }
    - { role: packages, packages: "{{ site_config.packages.utils_media }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_mgmt }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_normalwork }}" }
    - { role: packages, packages: "{{ site_config.packages.utils_python2 }}", when: "utils_python2 is defined" }
    - { role: packages, packages: "{{ site_config.packages.utils_python3 }}" }
    - { role: nfs-client, nfsv3_target: "{{ site_config.nfs.common }}" }

