---
- hosts: all
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - system-accounts
    - iptables
    - role: packages
      packages: "{{ site_config.packages.sitewide }}"
    - cron-apt
    - role: ntp
      when: "server_ntp is undefined"
    - role: rsyslog-client
      when: "server_rsyslog is undefined"
    - role: exim4
      when: "server_smarthost is undefined"
    - role: nfs-client
      when: "nfsv3_target is defined"

- hosts: server
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: ntp-server, when: "server_ntp is defined" }
    - { role: rsyslog-server, when: "server_rsyslog is defined" }
    - { role: ldap-server, when: "server_ldap is defined" }
    - { role: dnsmasq, when: "server_dnsmasq is defined" }
- hosts: gateway
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - ssh-gateway

- hosts: virt-host
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - virt-server
- hosts: virt-client
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - virt-client

- hosts: actor
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - eups
- hosts: privca
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - privca

- hosts: hwraid
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - hwraid
- hosts: fc-nfs
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - iscsi
    - nfs-server
- hosts: landfill
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - boot-aptupdate
    - serial-console
    - { role: packages, packages: "{{ host_packages }}" }

- hosts: prometheus-exporters
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  vars_prompt:
    - name: "prometheus_exporters_mysql_account"
      prompt: "Enter account information for mysql in \"<account>:<password>\" format\n  need 'select' and 'replication client' priv on *.*\n  just type enter when you don't configure"
      private: yes
    - name: "prometheus_exporters_pgsql_account"
      prompt: "Enter account information for pgsql in \"<account>:<password>\" format\n  need connection priv on postgres\n  just type enter when you don't configure"
      private: yes
  roles:
    - prometheus-exporters

- hosts: jupyter
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - jupyter

