---
- name: Add backports
  become: yes
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_lsb.codename }}-backports main contrib non-free"
    state: present
    update_cache: yes
  when: packages_setup_backport is defined and ansible_lsb.release != 'testing'

- name: Install packages via apt
  become: yes
  apt:
    update_cache: yes
    name: "{% if item.package is defined %}{{ item.package}}{% else %}{{ item }}{% endif %}"
    state: present
  with_items: "{{ packages }}"
- name: Enable service via systemd
  become: yes
  systemd:
    name: "{{ item.enable_service }}.service"
    enabled: yes
    state: started
  when: item.enable_service is defined
  with_items: "{{ packages }}"

