---
- name: Configure mailname
  become: yes
  lineinfile:
    dest: "/etc/mailname"
    line: "{{ postfix.mailname }}"
    regexp: "^.*"
  notify: restart postfix
  when: postfix.mailname is defined
- name: Configure iptables v4
  become: yes
  lineinfile:
    dest: "/etc/iptables/rules.v4"
    line: "{{ item }}"
    insertafter: "^# ANSIBLE_ROLE_FILTER_PLACE"
  with_items:
    - "-A INPUT -p tcp -m tcp --dport 25 -j ACCEPT"
  notify: restart iptables-persistent
- name: Configure iptables v6
  become: yes
  lineinfile:
    dest: "/etc/iptables/rules.v6"
    line: "{{ item }}"
    insertafter: "^# ANSIBLE_ROLE_FILTER_PLACE"
  with_items:
    - "-A INPUT -p tcp -m tcp --dport 25 -j ACCEPT"
  notify: restart iptables-persistent

