---
- name: Add nodesource apt-key
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
- name: Add nodesource apt line
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_10.x {{ ansible_lsb.codename }} main"
    state: present
    update_cache: yes
- name: Install nodejs
  become: yes
  apt:
    name: nodejs

