---
- name: configure backup for slapd
  become: yes
  cron:
    minute: 5
    hour: 0
    job: "{{ site_config.system_dirs.git_clone }}/github.com/Subaru-PFS/pfs_infra_ipmu/admin-script/ldap-backup.sh"
    cron_file: "/etc/crontab"
    user: root
    name: backup-ldap
  when: install_backup_ldap is defined

