---
- name: Create local directories
  become: yes
  file:
    path: "{{ item.target }}"
    state: directory
    mode: 0755
  with_items: "{{ local_uuids }}"
- name: Mount UUIDs
  become: yes
  mount:
    name: "{{ item.target }}"
    state: mounted
    src: "UUID={{ item.source }}"
    fstype: "{{ item.fstype }}"
    passno: 2
    opts: "{% if item.option is defined %}{{ item.option }}{% else %}defaults{% endif %}"
  with_items: "{{ local_uuids }}"

