---
- name: restart mariadb
  systemd: 
    name: mariadb.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
- name: restart mysql
  systemd: 
    name: mysql.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
