- name: Configure iptables for localnet
  become: yes
  lineinfile:
    dest: "/etc/iptables/rules.v4"
    line: "-A INPUT -s {{ site_config.localnet.addr }} -j INTERNAL"
    insertafter: "^# ANSIBLE_ROLE_FILTER_PLACE"
  notify: restart iptables-persistent
  when: site_config.localnet is defined

