---
- name: Remove README in dnsmasq.d
  become: yes
  file:
    path: "/etc/dnsmasq.d/README"
    state: absent
- name: Checkout target dnsmasq config github repository
  git:
    repo: "{{ site_config.dnsmasq.git_repo }}"
    dest: "/etc/dnsmasq.d/"
    accept_hostkey: yes
    key_file: "{{ site_config.git.key_file }}"
    update: yes
    force: yes
    version: "{% if site_config.dnsmasq.git_branch is defined %}{{ site_config.dnsmasq.git_branch }}{% else %}HEAD{% endif %}"
  notify: restart dnsmasq
- name: Make symlink to dnsmasq-site
  become: yes
  file:
    src: "/etc/dnsmasq.d/dnsmasq-site.{{ site_config.dnsmasq.site }}"
    dest: "/etc/dnsmasq.d/dnsmasq-site.conf"
    state: link
  when: site_config.dnsmasq.site is defined
- name: dnsmasq service config
  become: yes
  lineinfile:
    dest: "/etc/default/dnsmasq"
    regexp: "^CONFIG_DIR="
    insertafter: "^#CONFIG_DIR"
    line: "CONFIG_DIR=/etc/dnsmasq.d,*.conf"
  notify: restart dnsmasq
- name: iptables checksum-fill
  become: yes
  lineinfile:
    dest: "/etc/iptables/rules.v4"
    insertafter: "^# ANSIBLE_ROLE_MANGLE_PLACE"
    line: "-A POSTROUTING -p udp --dport bootpc -j CHECKSUM --checksum-fill"
  notify: restart iptables-persistent

