---
- name: set fact
  set_fact:
    ntp_conf_dest: "{{ '/etc/' + ntp_confdir + '/ntp.conf' }}"
  when: "ntp_confdir is defined"
- name: set fact
  set_fact:
    ntp_conf_dest: "{{ '/etc/ntp.conf' }}"
  when: "ntp_confdir is not defined"
- name: NTP config remove pools
  become: yes
  lineinfile:
    dest: "{{ ntp_conf_dest }}"
    regexp: "^pool"
    state: absent
  notify: restart ntp
  when: "site_config.ntp.local is defined"
- name: NTP config add server lines
  become: yes
  lineinfile:
    dest: "{{ ntp_conf_dest }}"
    regexp: "^server"
    insertafter: "^#server"
    line: "server {{ item }}"
  with_items: "{{ site_config.ntp.local }}"
  notify: restart ntp
  when: "site_config.ntp.local is defined"

