#! /bin/sh
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
  set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

### BEGIN INIT INFO
# Provides: {{ exporter.name }}
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prometheus exporter
# Description:       Prometheus exporter
### END INIT INFO

DSEC="Prometheus exporter {{ exporter.name }} (by ansible init.d)"
DAEMON=/usr/sbin/{{ exporter.name }}
NAME={{ exporter.name }}
USER=root
PIDFILE=/var/run/prometheus/{{ exporter.name }}.pid

ARGS=""
[ -r /etc/default/{{ exporter.name }} ] && . /etc/default/{{ exporter.name }}

HELPER=/usr/bin/daemon
HELPER_ARGS="--name=$NAME --pidfile=$PIDFILE --user=$USER --stdout=daemon.debug --stderr=daemon.err"

do_start_prepare()
{
  mkdir -p `dirname $PIDFILE` || true
}

do_start_cmd()
{
  $HELPER $HELPER_ARGS --running && return 1
  $HELPER $HELPER_ARGS -- $DAEMON $ARGS || return 2
  return 0
}

do_stop_cmd()
{
  $HELPER $HELPER_ARGS --running || return 1
  $HELPER $HELPER_ARGS --stop || return 2
  for c in 1 2 3 4 5; do
    sleep 1
    $HELPER $HELPER_ARGS --running || break
  done
  $HELPER $HELPER_ARGS --running || return 0
  return 2
}

